# Generated by Django 5.0.6 on 2024-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile', models.PositiveBigIntegerField()),
                ('dob', models.TextField()),
                ('addr', models.TextField()),
                ('service_type', models.CharField(default='', max_length=100)),
                ('curr_date', models.TextField()),
                ('image', models.ImageField(default=' ', upload_to='media/cus_img')),
                ('application_no', models.PositiveBigIntegerField()),
                ('user', models.CharField(default='', max_length=100)),
                ('remark', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test')),
            ],
        ),
    ]
